config/routes.rb
Phphoto::Application.routes.draw do
  devise_for :admins
  resources :posts

  get '/portfolio' => 'pages#portfolio'
  get '/portfolio/:id' => 'galleries#show', as: "galleries"

  resources :photos

  scope :admin do
    resources :galleries
  end

  root :to => 'pages#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, styles: {thumb: "x300>", sm_thumb: "x200>", sm_square: "100x100>", square: "300x300>"}
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  belongs_to :gallery
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < ApplicationController
  before_action :authenticate_admin!
  layout "default"
  def index
    @galleries = Gallery.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  layout "default"
  def show
    @gallery = Gallery.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    redirect_to galleries_path if admin_signed_in?
  end

  def portfolio
    @galleries = Gallery.all
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  layout "default"
  def show
    @photo = Photo.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  before_action :configure_permitted_parameters
  def sign_in
  end

  def logout
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_format(time)
    time.strftime("%m/%d/%y %I:%M%P")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/galleries/index.html.haml
%h2 Galleries
%table
  %thead
    %tr
      %th Name
      %th Photos
      %th Created
  %tbody
    - @galleries.each do |gallery|
      %tr
        %td
          %strong
            = gallery.name
        %td #{gallery.photos.count} photos
        %td= time_format(gallery.created_at)

app/views/galleries/show.html.haml
%h2= @gallery.name
.gallery-thumbs
  - @gallery.photos.each do |photo|
    .photo-wrapper
      = link_to photo_path(photo) do
        = image_tag photo.image.url(:square)

app/views/layouts/application.html.haml
!!!
%html
  %head
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %link{href: "http://fonts.googleapis.com/css?family=Alfa+Slab+One|Cabin|News+Cycle|Federo|Quicksand|Paytone+One|Wire+One|Tenor+Sans|Anton|Amethysta|Vollkorn|Francois+One|Marvel|Hammersmith+One", rel: "stylesheet", type: "text/css"}
    %link{href: "http://fonts.googleapis.com/css?family=Allura", rel: "stylesheet", type: "text/css"}
    %link{href: "http://fonts.googleapis.com/css?family=Quicksand:300|Marvel", rel: "stylesheet", type: "text/css"}
    %link{href: "http://fonts.googleapis.com/css?family=Open+Sans:400,300", rel: "stylesheet", type: "text/css"}
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Professional Web Design and Photography
    = render 'shared/googlefonts'

    %title Patrick Holloway

    = render 'shared/fixed_header'
  
    .spacer

  %body
    = yield 

app/views/layouts/default.html.haml
!!!
%html
  %head
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %link{href: "http://fonts.googleapis.com/css?family=Alfa+Slab+One|Cabin|News+Cycle|Federo|Quicksand|Paytone+One|Wire+One|Tenor+Sans|Anton|Amethysta|Vollkorn|Francois+One|Marvel|Hammersmith+One", rel: "stylesheet", type: "text/css"}
    %link{href: "http://fonts.googleapis.com/css?family=Allura", rel: "stylesheet", type: "text/css"}
    %link{href: "http://fonts.googleapis.com/css?family=Quicksand:300|Marvel", rel: "stylesheet", type: "text/css"}
    %link{href: "http://fonts.googleapis.com/css?family=Open+Sans:400,300", rel: "stylesheet", type: "text/css"}
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Professional Web Design and Photography
    = render 'shared/googlefonts'

    %title Patrick Holloway

    = render 'shared/fixed_header'
  
    .spacer

  %body
    #container
      #center_column
        .logo_box
          %a{href: "/"}
            = image_tag "PHPlogo.png"
        #center_column_headng
        #navbar
          %a{href: "/portfolio.html"} Photography
          / %a{href: "webdesign.html"} Web Design
        #page_title_container
          %h1#page_title patrick holloway
        #main_content
          = yield
        #footer
          ©2014 Patrick Holloway Photography • Lowell MA 01852 • patrickjholloway@gmail.com

app/views/pages/_photo_navbar.html.erb
<a href="#">SHOP</a>
<a href="#">FAQ</a>
<a href="#">PHOTO STREAM</a>
<a href="#">PORTFOLIO</a>

app/views/pages/_web_design_navbar.html.erb
<a href="#">WEB DESIGN</a>
<a href="#">FAQ</a>
<a href="#">PORTFOLIO</a>
<a href="#">SERVCES</a>

app/views/pages/index.html.haml
#container
  #center_column
    .logo_box
      %a{href: "/"}
        = image_tag "PHPlogo.png"
    #center_column_headng
    #navbar
      %a{href: "portfolio.html"} Photography
      / %a{href: "webdesign.html"} Web Design
    #page_title_container
      %h1#page_title patrick holloway
    #main_content
      .image_gallery
        = image_tag "_MG_0057.jpg"
      #INTRO.classy
        %h2 Welcome
        %p Patrick Holloway is a photographer and web devloper based in Lowell, MA. He is a rugged woodsman, a loving husband, and he loves him some good hip hop.
      #SERVS.classy.right
    #footer
      ©2014 Patrick Holloway Photography • Lowell MA 01852 • patrickjholloway@gmail.com

app/views/pages/portfolio.html.haml
#container
  #center_column
    .logo_box
      %a{href: "/"}
        = image_tag "PHPlogo.png"
    #center_column_headng
    #navbar
      %a{href: "/about"} ABOUT
      %a{href: "/portfolio"} PORTFOLIO
    #page_title_container
      %h1#page_title patrick holloway photography

    #main_content
      %h1 PORTFOLIO : :
        - @galleries.each do |gallery|
          .gallerylink
            = link_to galleries_path(gallery) do
              -if gallery.photos.any?
                = image_tag gallery.photos.first.image.url(:thumb)
            %h3= gallery.name
  #footer
    ©2012 Patrick Holloway Photography • Medford MA 02155 • 781.960.3127 • patrickjholloway@gmail.com

app/views/photos/show.html.haml
%h2= @photo.gallery.name
.fullpic
  = image_tag @photo.image.url

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_fixed_header.html.haml
#fixed_header
  #header
    %span.header_logo PH
    %a{href: "#"} HOME
    %a{href: "#"} ABOUT
    %a{href: "#"} PHOTOGRAPHY
    %a{href: "#"} CONTACT

app/views/shared/_googlefonts.html.erb
<link href='http://fonts.googleapis.com/css?family=Alfa+Slab+One|Cabin|News+Cycle|Federo|Quicksand|Paytone+One|Wire+One|Tenor+Sans|Anton|Amethysta|Vollkorn|Francois+One|Marvel|Hammersmith+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Allura' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Quicksand:300|Marvel' rel='stylesheet' type='text/css'>